version: '3'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    environment:
     AWS_ACCESS_KEY: "${AWS_ACCESS_KEY}"
     AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: example